---
roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
    version: "7.6.0"

  - name: geerlingguy.pip
    src: https://github.com/geerlingguy/ansible-role-pip
    version: "3.1.0"

  - name: stuvusIT.systemd-timesyncd
    src: https://github.com/stuvusIT/ansible_systemd_timesyncd
    version: master

  - name: systemd-resolved
    src: https://github.com/ho-ansible/systemd-resolved
    version: master

collections:
  - name: https://github.com/avryez/sshd_config_manager.git
    type: git
    version: "v1.5.1"
