---
- name: DOCKER - Certbot Image
  docker_image:
    name: certbot/dns-route53:latest
    source: pull

- name: CRON - Certbot Certficate Renewal
  cron:
    name: Certbot Certificate Renewal
    minute: "0"
    hour: "3"
    job: "docker run --rm -v '/opt/config/nginx/ssl:/config' -v '/opt/config/aws:/root/.aws' certbot/dns-route53 --config-dir /config renew >> /var/log/certbot.log"

- name: CRON - Restart Nginx
  cron:
    name: Restart Nginx
    minute: "15"
    hour: "3"
    job: "docker stop nginx && docker start nginx >> /var/log/certbot.log"

- name: CRON - Backup
  cron:
    name: Backup
    minute: "0"
    hour: "4"
    day: "1"
    job: "docker run --rm -v '/data:/data' -v '/opt/config/backup/backup.sh:/usr/sbin/backup' base backup > /var/log/backup.log"

- name: CRON - Plex Cleaner
  cron:
    name: Plex Cleaner
    minute: "30"
    hour: "3"
    job: "docker run --rm -v '/opt/config/plex-cleaner:/plex-cleaner' -v '/data/shares/Media:/media' base /plex-cleaner/PlexCleaner.py >> /dev/null"
...
