---
- name: DOCKER - MakeMKV
  docker_container:
    name: makemkv
    image: jlesage/makemkv
    pull: "always"
    volumes:
      - /data/config/makemkv:/config:rw
      - /data/shares/Media:/output:rw
      - /data/shares/Downloads:/storage:rw
    restart_policy: always
...
