---
- name: DOCKER - Minecraft
  docker_container:
    name: minecraft
    image: itzg/minecraft-bedrock-server
    pull: "always"
    memory: 8192M
    memory_swap: unlimited
    network_mode: host
    interactive: true
    tty: true
    env:
      GID: "65534"
      UID: "65534"
      EULA: "true"
    volumes:
      - /data/config/minecraft:/data:rw
    restart_policy: always
...
