---
- name: DOCKER - Plex
  docker_container:
    name: plex
    image: plexinc/pms-docker
    pull: true
    memory: 4096M
    memory_swap: unlimited
    network_mode: host
    env:
      TZ: "America/New_York"
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
      PLEX_UID: "65534"
      PLEX_GID: "65534"
    devices:
      - /dev/dri/card1:/dev/dri/card1:rwm
      - /dev/dri/renderD128:/dev/dri/renderD128:rwm
    volumes:
      - /opt/config/plex:/config:rw
      - /data/shares/Media:/media:rw
      - /tmp:/tmp:rw
    restart_policy: always
...
