---
- name: DOCKER - Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: "always"
    memory: 512M
    memory_swap: unlimited
    network_mode: container:openvpn-client
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /data/config/radarr:/config:rw
      - /data/shares/Media:/media:rw
      - /data/shares/Downloads:/downloads:rw
    restart_policy: always
...
