---
- name: DOCKER - Samba
  docker_container:
    name: samba
    image: dockurr/samba
    pull: "always"
    memory: 512M
    memory_swap: unlimited
    network_mode: host
    env:
      NMBD: "true"
    volumes:
      - /data/shares:/shares:rw
      - /data/config/samba/smb.conf:/etc/samba/smb.conf:rw
      - /data/config/samba/users.conf:/etc/samba/users.conf:rw
    restart_policy: always
...
