---
- name: SYSTEM - Create 'skingry' user
  user:
    name: "skingry"
    state: present
    comment: "Seth Kingry"
    groups:
    - "docker"
    - "sudo"
    create_home: true
    home: "/home/skingry"
    shell: "/bin/zsh"

- name: SYSTEM - Set authorized key for 'skingry'
  authorized_key:
    user: "skingry"
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICXxXNff7rnagGbKPOfABUlmoCOI+Y8q4QQUcj004Ixz seth.kingry@LXVNPG6HMH"
...
