---
- name: DOCKER - Tautulli
  docker_container:
    name: tautulli
    image: linuxserver/tautulli
    pull: "always"
    memory: 256M
    memory_swap: unlimited
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /data/config/tautulli:/config:rw
      - "/data/config/plex/Library/Application Support/Plex Media Server/Logs:/logs"
    restart_policy: always
...
