- name: Certbot Certficate Renewal
  cron:
    name: Certbot Certificate Renewal
    minute: "0"
    hour: "3"
    job: "docker run --rm --name certbot -v '/opt/config/nginx/ssl:/config' -v '/opt/config/aws:/root/.aws' certbot/dns-route53 --config-dir /config renew >> /var/log/certbot.log"

- name: Restart Nginx
  cron:
    name: Restart Nginx
    minute: "15"
    hour: "3"
    job: "docker stop nginx && docker start nginx >> /var/log/certbot.log"

- name: Backup
  cron:
    name: Backup
    minute: "0"
    hour: "4"
    day: "1"
    job: "docker run --rm --name backup -v '/data:/data' -v '/opt/config/backup/backup.sh:/usr/sbin/backup' base backup > /var/log/backup.log"
