---
- name: Pull and configure container
  docker_container:
    name: tautulli
    image: linuxserver/tautulli
    pull: true
    memory: 256M
    memory_swap: unlimited
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /opt/config/tautulli:/config:rw
      - "/opt/config/plex/Library/Application Support/Plex Media Server/Logs:/logs"
    restart_policy: always
