- name: Install zsh
  package:
    name: zsh
    state: present

- name: Install net-tools
  package:
    name: net-tools
    state: present

- name: Install neofetch
  package:
    name: neofetch
    state: present

- name: Allow passwordless sudo for 'sudo' group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo\tALL'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: update sshd config
  update_sshd_config:
    password_authentication: false
    permit_root_login: "no"
    port: 1471
    restart_service: yes
